### ISSUE TITLE
Use Nextcloud's background jobs

### ISSUE THREAD

**Issue by kolaente** [nextcloud/previewgenerator#205] opened 2020-09-21 20:37 UTC
It would be great if the preview generator could use the [background job feature already provided by nextcloud](https://docs.nextcloud.com/server/latest/developer_manual/basics/backgroundjobs.html) instead of requiring users to set up a cron job for generating preview images. Registering cron jobs is not always easy and error prone (see [here](https://github.com/rullzer/previewgenerator/issues/176) and [here](https://help.nextcloud.com/t/docker-setup-cron/78547/8). Since nextcloud already provides a mechanism to run cron jobs, that could be used.

**Comment by strugee** [comment] 2020-09-23 07:33
See https://github.com/rullzer/previewgenerator#why-cant-i-use-webcron. Using Nextcloud's background job feature could lead to errors in many cases.

**Comment by kolaente** [comment] 2020-09-24 05:58
But only if users are using webcron? The nextcloud docker image for example already has a proper Cron set up (it does not use webcron) but generating the previews through Cron requires me to manually set up another one which is more hassle. In that case (maybe that's a niche anyway?) it would be easier to just use the already present Cron.

**Comment by strugee** [comment] 2020-09-26 07:10
Duplicate of #1, I believe.

**Comment by dekiesel** [comment] 2020-10-19 12:42
In case somebody has a docker-friendly solution I'd be really happy to hear it!

**Comment by blacs30** [comment] 2020-12-03 22:25
In Kubernetes I run a CronJob this way:

```
con.withCommand(['kubectl']) +
con.withArgs(['exec','-it', 'nextcloud-0' ,'--', 'php', '-f', '/var/www/html/cron.php']);
```

First I was using webcron but that didn't work as the instance was getting too big.

The above approach would work in a same way for the preview generator, for docker just use the proper commands.

**Comment by Gotisch** [comment] 2021-01-12 01:01
I also wanted to use the included cronjob variant and web cron and there are multiple possibilities!

You could use max_execution_time or a configentry to let user configure the approximative maximum duration of one call to pre-generate.
I implemented this to try it out and it works ok (for me at least). 

Normally you do not upload huge amounts of images on systems that rely on web-cron anyway imo. 
Of course if someone uploads GBs of images it will take a while before the previews are pregenerated, but worst case the previews are generated, when the users looks at the images.

caveat is that webcron only runs 1 Task per call, so it might take a long while to pregenerate using that methods (pregenerate job will just be one of many. On my instance there where 25 other jobs and webcron was only called once every 5 minutes, so effectively the pregenerate job was only called every 125 Minutes)

The code changes i did are sketched below (I also moved most of the logic into a server just to have less code duplication):
https://gist.github.com/Gotisch/e11927f2bad3425abd4c59e6ffb2d2f7

Maybe something that can be added?

**Comment by mayermart** [comment] 2021-04-25 16:56
As an example the "Maps"-App simply adds a job to oc_jobs per picture to geolocate it, even if there are thousands of pictures.
As of https://github.com/nextcloud/server/issues/22730 Nextcloud executes one job of oc_jobs only when called via Webcron, whereas multiple jobs get executed when called by cron.

Maybe that could be an option to implement.
On Installation add add all files to the jobs queue.
On detecting new files add a new job to the jobs queue.

**Comment by dakontiva** [comment] 2021-08-19 22:15
This would be a very helpful feature for those like me who are self hosting with a nextcloud provider. Most providers only provide nextcloud admin access but dont give admin access to the vps. However they support cron background jobs for even the basic plans, so if this app can use nextcloud cron background jobs instead of having to create a system cron job manually that would be very helpful.

**Comment by st3iny** [comment] 2022-06-10 12:07
Duplicate of https://github.com/nextcloud/previewgenerator/issues/1

**Closed by st3iny** 2022-06-10 12:07 UTC
Labels: duplicate
