### ISSUE TITLE
Why cron.php is not used for background work?

### ISSUE THREAD

**Issue by fandjelo** [nextcloud/previewgenerator#130] opened 2018-09-22 15:47 UTC
Hi, I have no clue about PHP or inner world of Nextcloud, however, I know that there is already a place called cron.php, where applications can register their background jobs. See: https://docs.nextcloud.com/server/13/admin_manual/configuration_server/background_jobs_configuration.html

Why doesn't this application make use of it and we have to do additional call in crontab?

**Comment by pmow** [comment] 2018-12-21 14:02
the docker doesn't provide for custom crons, so any custom one gets wiped out after an upgrade - registering with cron.php would be ideal

**Comment by hypervtechnics** [comment] 2019-11-19 09:30
Guessing there are no news here?

**Comment by skorokithakis** [comment] 2019-11-26 16:59
By the way, you can run docker with cron with:

`/usr/bin/docker exec -u www-data -it `docker ps --filter "ancestor=nextcloud" -q -l` php occ preview:pre-generate`

**Comment by st3iny** [comment] 2021-12-01 22:03
I agree that this would be a nice addition to the app. However, it will cause issues with cron services that will timeout (e.g. WebCron and AJAX) because the preview generation might run for a long time.

**Comment by dimm0** [comment] 2021-12-01 23:47
what issues?

**Comment by proletarius101** [comment] 2021-12-25 10:37
> I agree that this would be a nice addition to the app. However, it will cause issues with cron services that will timeout (e.g. WebCron and AJAX) because the preview generation might run for a long time.

You may use the "[register manually](https://docs.nextcloud.com/server/latest/developer_manual/basics/backgroundjobs.html#registering-manually)" path that by default only register the background job if the background job mode is cron

**Comment by proletarius101** [comment] 2021-12-27 04:33
See also https://github.com/nextcloud/news-updater

**Comment by st3iny** [comment] 2022-01-14 14:17
> what issues?

Background jobs are not meant to rung for a long time. They were designed for short running and small jobs like e.g. sending notifications emails. It would be possible to split the generation into small chunks and execute them one by one. However, this would require refactoring and time which I currently can't afford.

**Comment by st3iny** [comment] 2022-06-10 12:07
Duplicate of https://github.com/nextcloud/previewgenerator/issues/1

**Closed by st3iny** 2022-06-10 12:07 UTC
