### ISSUE TITLE
PreviewGenerator stops on some jpeg files with error „could not create folder“

### ISSUE THREAD

**Issue by Arnesbuddy** [nextcloud/previewgenerator#239] opened 2021-06-21 07:22 UTC
Hello!

My surveillance cams pushes pictures through FTP to Raspberry Pi (1TB SSD USB3 on the pi)
NC runs on the same Pi. External Folders for the different folders are set up an work. Using the iOS NC App, the preview creation of images works, but slow. 
So far so good.

Trying out preview generator and running into an unexpected behavior. There are some faulty folders existing in preview folder structure, the 
initial ./occ preview:generate-all -vvv runs into an error (in folder .php line 176) 

![3027BF82-8D23-4E8D-97AA-2EEFF6EB50A4](https://user-images.githubusercontent.com/75087207/122722420-ffd1a980-d271-11eb-9121-54b446b55c39.jpeg)

and stopped the preview creation process. When I delete corresponding faulty folder mentioned in the log and restart ./occ preview:generate-all -vvv again, the process goes on, until the next error occurs. 
All Sw in the latest official release.

Could this behavior get some error handling process, that simply skips / delete the preview folder if it is not possible to create instead of terminating the process?

Ty in advance :)

**Comment by RisedSky** [comment] 2021-06-23 13:21
> Hello!
> 
> My surveillance cams pushes pictures through FTP to Raspberry Pi (1TB SSD USB3 on the pi)
> NC runs on the same Pi. External Folders for the different folders are set up an work. Using the iOS NC App, the preview creation of images works, but slow.
> So far so good.
> 
> Trying out preview generator and running into an unexpected behavior. There are some faulty folders existing in preview folder structure, the
> initial ./occ preview:generate-all -vvv runs into an error (in folder .php line 176)
> 
> ![3027BF82-8D23-4E8D-97AA-2EEFF6EB50A4](https://user-images.githubusercontent.com/75087207/122722420-ffd1a980-d271-11eb-9121-54b446b55c39.jpeg)
> 
> and stopped the preview creation process. When I delete corresponding faulty folder mentioned in the log and restart ./occ preview:generate-all -vvv again, the process goes on, until the next error occurs.
> All Sw in the latest official release.
> 
> Could this behavior get some error handling process, that simply skips / delete the preview folder if it is not possible to create instead of terminating the process?
> 
> Ty in advance :)

Are you sure the user who do this task has all the permission ?

**Comment by Arnesbuddy** [comment] 2021-06-23 18:09
Permissions are ok - it is basically about error handling if some errors occur. I have cleaned up the preview folder and now it runs without errors. 
Imho it would be nice to let the script run until the end and post errors in a log. No need to run into an an error that ends the script. 

Thank you for your response!

**Comment by skjnldsv** [comment] 2022-03-07 10:10
duplicate of https://github.com/nextcloud/previewgenerator/issues/289

**Closed by skjnldsv** 2022-03-07 10:10 UTC
