### ISSUE TITLE
FIle-Type Black-/Whitelist

### ISSUE THREAD

**Issue by ausbonn** [nextcloud/previewgenerator#170] opened 2019-08-25 13:29 UTC
Hi!

I really like preview-generator however, it would be quite nice to have the possibility to limit file-types, a preview is generated for, to dedicated types, e.g.

limit preview generation to: *.jpg, *.png, ...
... or limit to dedicated file-names: "-name *.jpg,*.png,2019*.jpg"

and exclude file-types from preview-generation, eg.: *.cr2, *.raw, *.img, *.iso ...
like "-exclude *.cr2,*.raw,*.img,*.iso"

Why?

I have a quite huge collection of images containing terrabytes of RAW-Images (CR2). However, I'd like to get previews for the jpgs only, so whitelistening would be fine.

**Comment by Atlantis1979** [comment] 2019-09-27 04:26
I'd love this too. I have multi-gigabyte TIFF files that I don't need indexed for no reason.

**Comment by OdinsAuge** [comment] 2019-10-17 10:40
I have also a lot of RAW images, so this would be great.

**Comment by eibex** [comment] 2020-01-08 23:08
Isn't this already do-able? See first comment to #129

**Comment by st3iny** [comment] 2021-11-10 13:01
The app uses the preview setting from the server. See my response at https://github.com/nextcloud/previewgenerator/issues/169#issuecomment-965106455 for more info.

I'm closing this issue because it's a duplicate of #169 and what @eibex said.

**Closed by st3iny** 2021-11-10 13:01 UTC
