### ISSUE TITLE
Not working on Nextcloud 22.1.1

### ISSUE THREAD

**Issue by lerd2805** [nextcloud/previewgenerator#250] opened 2021-09-01 16:59 UTC
Hi, I have Nextcloud 22.1.1 and previewgenerator is not working anymore.

Check all my apps and it's activated: 

www-data@6bbd20c3e6da:~/html$ php occ app:list
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Enabled:
  - accessibility: 1.7.0
  - activity: 2.15.0
  - admin_audit: 1.11.0
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.18.0
  - duplicatefinder: 0.0.11
  - federatedfilesharing: 1.11.0
  - files: 1.16.0
  - files_downloadactivity: 1.11.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.13.2
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.11.0
  - group_default_quota: 0.1.2
  - logreader: 2.7.0
  - lookup_server_connector: 1.9.0
  - notifications: 2.10.1
  - oauth2: 1.9.0
  - password_policy: 1.12.0
  - previewgenerator: 3.1.1
  - privacy: 1.6.0
  - provisioning_api: 1.11.0
  - recommendations: 1.1.0
  - registration: 1.3.0
  - serverinfo: 1.12.0
  - settings: 1.3.0
  - systemtags: 1.11.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.1
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.6.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.1
 
Disabled:
  - circles
  - encryption
  - federation
  - files_external
  - files_pdfviewer
  - firstrunwizard
  - nextcloud_announcements
  - photos
  - sharebymail
  - support
  - survey_client
  - text
  - unsplash
  - user_ldap

**Comment by xkill** [comment] 2021-09-21 13:23
Duplicate #243

**Comment by xkill** [comment] 2021-09-23 11:10
Should be fixed with Commit f51832758b877d5f4d2883059664578b3efc34cc

**Comment by mrplug** [comment] 2021-09-24 10:16
When will it be available in the Nextcloud App Store?

**Comment by bcutter** [comment] 2021-10-04 20:40
> 
> 
> When will it be available in the Nextcloud App Store?

Copy that - when? Estimation?

**Comment by st3iny** [comment] 2021-11-02 10:25
Duplicate of https://github.com/nextcloud/previewgenerator/issues/240.

**Closed by st3iny** 2021-11-02 10:25 UTC
