### ISSUE TITLE
libpng warning while running "preview:pre-generate-all"

### ISSUE THREAD

**Issue by stratege1401** [nextcloud/previewgenerator#120] opened 2018-06-16 10:23 UTC
uname -a
Linux 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux

netxcloud 13.0.4 fresh install
Preview Generator	1.0.9
PHP 7.0.27-0+deb9u1
    with Zend OPcache v7.0.27-0+deb9u1

I have read #91 but i am not sure it is related to php7

While scanning/generating i am getting this error from times to times:
`

.............
Scanning folder /google-xxxxxxxxxx/files/Dropbox/LinuxSTUFF

Scanning folder /google-xxxxxxxxxx/files/Dropbox/LinuxSTUFF/deb93

Scanning folder /google-xxxxxxxxxx/files/Dropbox/LinuxSTUFF/one5

libpng warning: Interlace handling should be turned on when using png_read_image

Scanning folder /google-xxxxxxxxxx/files/Dropbox/LinuxSTUFF/torsav
............

`

This is my packages list for libpng on my system, do i miss something ??

libpng-sixlegs-java:
  Installé : 2.0-1
libpng-dev:
  Installé : 1.6.28-1
libpnglite0:
  Installé :  0.1.17-2
libpnglite-dev:
  Installé :  0.1.17-2
libpng-tools:
  Installé : 1.6.28-1
libpng16-16:
  Installé : 1.6.28-1
libpng++-dev:
  Installé : 0.2.9-1

**Comment by Ramalama2** [comment] 2018-10-12 16:56
exactly same here!

**Comment by oscarcarlsson** [comment] 2018-11-05 10:46
Possibly related? https://sourceforge.net/p/libpng/bugs/165/

**Comment by runout-at** [comment] 2019-05-22 13:34
same with latest:
  debian stable (stretch)
  php 7.0.33-0+deb9u3
  libpng16-16 1.6.28-1+deb9u1

Cron <www-data@...> php -f /var/www/nextcloud/occ preview:pre-generate
libpng warning: Interlace handling should be turned on when using png_read_image
...

**Comment by joshtrichards** [comment] 2024-03-30 14:58
Duplicate of nextcloud/server#27290

**Closed by joshtrichards** 2024-03-30 14:58 UTC
