### ISSUE TITLE
STL file preview ?

### ISSUE THREAD

**Issue by Maouu** [nextcloud/previewgenerator#390] opened 2023-05-05 13:06 UTC
Hello,
It's possible to preview STL file ? (in fact I dreams of STL, STP, STEP, OBJ)
This is 3D print files

Something like this : https://github.com/unlimitedbacon/stl-thumb but for Nextcloud

Thanks you

**Comment by st3iny** [comment] 2023-05-10 13:19
This is currently not possible.

Please open a [feature request](https://github.com/nextcloud/server/issues/new?assignees=&labels=enhancement%2C+0.+Needs+triage&template=Feature_request.md) in the server repository if you'd like this feature to be implemented in the future.

I'm closing this as this request is out of scope for the previewgenerator app. All previews are generated by the server or by other custom apps. Previewgenerator is just triggering previews and doesn't actually generate the previews themselves.

Duplicate of https://github.com/nextcloud/previewgenerator/issues/388

**Closed by st3iny** 2023-05-10 13:19 UTC
Labels: wontfix
