### ISSUE TITLE
please ignore .@_thumb folders

### ISSUE THREAD

**Issue by ghost** [nextcloud/previewgenerator#159] opened 2019-04-30 09:44 UTC
please ignore .@_thumb folders.

the command: ./occ preview:generate-all -vvv
generate preview pictures from the windows preview pictures (.@thumb)...
my nextcloud server is very slooooowly therefore

can you fix it?

**Comment by cClaude** [comment] 2021-04-21 11:18
This request is very similar to https://github.com/rullzer/previewgenerator/issues/157

@ghost Could you put your comment on https://github.com/rullzer/previewgenerator/issues/157 and clone this issue ?

**Comment by joshtrichards** [comment] 2024-03-30 01:38
Duplicate of #157

**Closed by joshtrichards** 2024-03-30 01:38 UTC
