### ISSUE TITLE
Errors while creating previews

### ISSUE THREAD

**Issue by nemihome** [nextcloud/previewgenerator#179] opened 2020-01-21 18:16 UTC
**Description:**
While the job is running I'm getting this error several times.

javaldx failed!
Warning: failed to read path from javaldx

(process:24479): dconf-CRITICAL **: 19:05:52.335: unable to create directory '/home/admin/.cache/dconf': Permission denied.  dconf will not work properly.

![image](https://user-images.githubusercontent.com/60146462/72830905-04132500-3c82-11ea-8da5-4202f6b63c6d.png)

![image](https://user-images.githubusercontent.com/60146462/72831208-a9c69400-3c82-11ea-8239-a6d3eb0844fc.png)

The job is running with sudo.

sudo -u www-data php7.4  ./occ preview:generate-all

Is this a bug or is the reason because the command is running with www-data because of config file is owned by www-data?

**Environment**
Nextcloud 18
PHP 7.41
Apache 2 latest version

**Comment by nemihome** [comment] 2020-01-21 21:13
I should have searched better: This is an old problem:
https://github.com/rullzer/previewgenerator/issues/154

**Comment by joshtrichards** [comment] 2023-06-21 15:55
This Issue can be closed out since it's covered in #154.

**Comment by st3iny** [comment] 2023-07-04 06:43
Duplicate of #154

**Closed by st3iny** 2023-07-04 06:43 UTC
Labels: duplicate
