### ISSUE TITLE
Broken HEIC Photos from iOS 18 (public beta)

### ISSUE THREAD

**Issue by edm00se** [nextcloud/previewgenerator#504] opened 2024-08-19 21:54 UTC
It would seem that since I installed the iOS Public Beta (I jumped on at public beta 2) my `.HEIC` image files aren't being handled properly. I can't view any of the new ones, except for a screenshot or video; **still images** aren't working. I can't view these in native Photos or in Memories either.

Errors are showing in logging such as:

```log
[core] Error: File: /{user}/files/{path}/2024-08-13_18-37-47_IMG_2964.HEIC Imagick says:
	GET /apps/memories/api/image/preview/324776?c=4c10576cd392d055b4fa5f8f26d9fb81&x=340&y=340&a=1
	from 135.131.135.20 by {user} at Aug 19, 2024, 4:33:52 PM

```

Assuming NC + Preview, etc. uses [libheif, it appears they had to update recently for the same reasons](https://github.com/strukturag/libheif/issues/1190). If there's something more I can check, I'd be happy to do so, but I don't believe this is something I can contribute a PR for.

~Currently running NC 29.0.4~ Persists ~on 29.0.5~ through 29.0.6. Here's what it looks like (urls redacted); regular photos don't show (including when viewing them not as a preview, aka I click on them), screenshot works, video works:

<img width="1437" alt="Screenshot 2024-08-21 at 12 11 13 PM Redacted" src="https://github.com/user-attachments/assets/1bcd749b-39e0-47e9-9a32-2315de36adac">

**Comment by joshtrichards** [comment] 2024-11-18 19:20
Duplicate of nextcloud/server#47289

**Closed by joshtrichards** 2024-11-18 19:20 UTC
