### ISSUE TITLE
Issue with complexe file paths and spaces

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [nextcloud/previewgenerator#278] opened 2021-12-27 12:27 UTC
Nextcloud Version: 22.2.3
Preview Generator Version: 3.4.1
OS: Ubuntu LTS 64 bit
PHP 8.0

Example Errors:
1.)
Movie preview generation failed Output: ["ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers"," built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)"," configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared"," libavutil 56. 31.100 / 56. 31.100"," libavcodec 58. 54.100 / 58. 54.100"," libavformat 58. 29.100 / 58. 29.100"," libavdevice 58. 8.100 / 58. 8.100"," libavfilter 7. 57.100 / 7. 57.100"," libavresample 4. 0. 0 / 4. 0. 0"," libswscale 5. 5.100 / 5. 5.100"," libswresample 3. 5.100 / 3. 5.100"," libpostproc 55. 5.100 / 55. 5.100","/var/www/nextcloud/data/user1/files/Archiev/Private/MC DONALDS/Music/BACKUP/Teste de la Creme - YouTube.mp4: No such file or directory"]

2.)
{"reqId":"eiipGTo8pXrUpcR7Zuwa","level":3,"time":"2021-12-30T12:44:56+00:00","remoteAddr":"HIDDEN","user":"USER","app":"core","method":"GET","url":"/nextcloud/index.php/core/preview?fileId=4395868&c=83090a319f4a81853948137f35021149&x=250&y=250&forceIcon=0&a=0","message":"unable to open image `/tmp/zeiterfassung februar.png': No such file or directory @ error/blob.c/OpenBlob/2874","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0","version":"22.2.3.0","exception":{"Exception":"ImagickException","Message":"unable to open image `/tmp/zeiterfassung februar.png': No such file or directory @ error/blob.c/OpenBlob/2874","Code":435,"Trace":[{"file":"/var/www/nextcloud/lib/private/Preview/Office.php","line":64,"function":"__construct","class":"Imagick","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/GeneratorHelper.php","line":62,"function":"getThumbnail","class":"OC\\Preview\\Office","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/Generator.php","line":245,"function":"getThumbnail","class":"OC\\Preview\\GeneratorHelper","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/Generator.php","line":140,"function":"getMaxPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/Generator.php","line":109,"function":"generatePreviews","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/nextcloud/lib/private/PreviewManager.php","line":189,"function":"getPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/nextcloud/core/Controller/PreviewController.php","line":169,"function":"getPreview","class":"OC\\PreviewManager","type":"->"},{"file":"/var/www/nextcloud/core/Controller/PreviewController.php","line":142,"function":"fetchPreview","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"getPreviewByFileId","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Preview/Office.php","Line":64,"CustomMessage":"--"},"id":"61cdb693747fd"}

3.)

{"reqId":"eiipGTo8pXrUpcR7Zuwa","level":3,"time":"2021-12-30T12:44:56+00:00","remoteAddr":"HIDDEN","user":"USER","app":"PHP","method":"GET","url":"/nextcloud/index.php/core/preview?fileId=4395868&c=83090a319f4a81853948137f35021149&x=250&y=250&forceIcon=0&a=0","message":"unlink(/tmp/zeiterfassung februar.png): No such file or directory at /var/www/nextcloud/lib/private/Preview/Office.php#68","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0","version":"22.2.3.0","exception":{"Exception":"Error","Message":"unlink(/tmp/zeiterfassung februar.png): No such file or directory at /var/www/nextcloud/lib/private/Preview/Office.php#68","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/lib/private/Preview/Office.php","line":68,"function":"unlink"},{"file":"/var/www/nextcloud/lib/private/Preview/GeneratorHelper.php","line":62,"function":"getThumbnail","class":"OC\\Preview\\Office","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/Generator.php","line":245,"function":"getThumbnail","class":"OC\\Preview\\GeneratorHelper","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/Generator.php","line":140,"function":"getMaxPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/Generator.php","line":109,"function":"generatePreviews","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/nextcloud/lib/private/PreviewManager.php","line":189,"function":"getPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/nextcloud/core/Controller/PreviewController.php","line":169,"function":"getPreview","class":"OC\\PreviewManager","type":"->"},{"file":"/var/www/nextcloud/core/Controller/PreviewController.php","line":142,"function":"fetchPreview","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"getPreviewByFileId","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"61cdb693748ec"}

**Comment by st3iny** [comment] 2022-01-14 11:39
Duplicate of https://github.com/nextcloud/server/issues/29296. The fix is at https://github.com/nextcloud/server/pull/29695. It will be included in the next update release of Nextcloud v21, v22 and v23.

**Closed by st3iny** 2022-01-14 11:39 UTC
