### ISSUE TITLE
Solution for Docker stateless deployments

### ISSUE THREAD

**Issue by iBobik** [nextcloud/previewgenerator#284] opened 2022-01-23 20:29 UTC
Docker deployments already run cron.php and does not support crontab customisation.

Could this app hook into Nextcloud's cron.php, so we does not need to create own Docker image?

**Comment by SchoolGuy** [comment] 2022-02-06 16:32
I would consider this a duplicate of

- https://github.com/nextcloud/previewgenerator/issues/1
- https://github.com/nextcloud/previewgenerator/issues/130
- https://github.com/nextcloud/previewgenerator/issues/205

**Comment by SchoolGuy** [comment] 2022-02-07 10:09
@st3iny Maybe we can clean this up too? :)

**Comment by st3iny** [comment] 2022-02-09 12:54
Duplicate of #1, #130 and #205. I will investigate this if I find some time for it.

**Closed by st3iny** 2022-02-09 12:54 UTC
