### ISSUE TITLE
Error with some pregenerated preview pictures

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [nextcloud/previewgenerator#282] opened 2022-01-18 06:58 UTC
Pictures exist and are shown, but the following is multiple times in **my logs:**

```
<html><body>
<!--StartFragment-->

  | core | ImagickException: unable to open image `/tmp/Talk 1.png': No such file or directory @ error/blob.c/OpenBlob/2874/var/www/nextcloud/lib/private/Preview/Office.php - line 64: Imagick->__construct()/var/www/nextcloud/lib/private/Preview/GeneratorHelper.php - line 62: OC\Preview\Office->getThumbnail()/var/www/nextcloud/lib/private/Preview/Generator.php - line 245: OC\Preview\GeneratorHelper->getThumbnail()/var/www/nextcloud/lib/private/Preview/Generator.php - line 140: OC\Preview\Generator->getMaxPreview()/var/www/nextcloud/lib/private/Preview/Generator.php - line 109: OC\Preview\Generator->generatePreviews()/var/www/nextcloud/lib/private/PreviewManager.php - line 189: OC\Preview\Generator->getPreview()/var/www/nextcloud/core/Controller/PreviewController.php - line 169: OC\PreviewManager->getPreview()/var/www/nextcloud/core/Controller/PreviewController.php - line 142: OC\Core\Controller\PreviewController->fetchPreview()/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 217: OC\Core\Controller\PreviewController->getPreviewByFileId()/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 126: OC\AppFramework\Http\Dispatcher->executeController()/var/www/nextcloud/lib/private/AppFramework/App.php - line 156: OC\AppFramework\Http\Dispatcher->dispatch()/var/www/nextcloud/lib/private/Route/Router.php - line 302: OC\AppFramework\App::main()/var/www/nextcloud/lib/base.php - line 1006: OC\Route\Router->match()/var/www/nextcloud/index.php - line 36: OC::handleRequest() |  
-- | -- | -- | --


<!--EndFragment-->
</body>
</html>
```

**Versions**

Nextcloud Server: 22.2.3
Preview Generator: 3.4.1
OS: Ubuntu 20.04 LTS x64
PHP: 8.0.14

**Comment by st3iny** [comment] 2022-01-18 14:24
Thanks for the report. Closing because it is a duplicate of https://github.com/nextcloud/server/issues/29956.

**Closed by st3iny** 2022-01-18 14:24 UTC
Labels: duplicate
