### ISSUE TITLE
ValueError: Invalid or uninitialized Zip object in /var/www/nextcloud/lib/private/Archive/ZIP.php:154

### ISSUE THREAD

**Issue by Germwalker** [nextcloud/previewgenerator#253] opened 2021-09-26 21:46 UTC
Something is stopping the generate-all process : 

```
An unhandled exception has been thrown:
ValueError: Invalid or uninitialized Zip object in /var/www/nextcloud/lib/private/Archive/ZIP.php:154
Stack trace:
#0 /var/www/nextcloud/lib/private/Archive/ZIP.php(154): ZipArchive->getStream()
#1 /var/www/nextcloud/lib/private/Preview/Bundled.php(42): OC\Archive\ZIP->extractFile()
#2 /var/www/nextcloud/lib/private/Preview/OpenDocument.php(44): OC\Preview\Bundled->extractThumbnail()
#3 /var/www/nextcloud/lib/private/Preview/GeneratorHelper.php(62): OC\Preview\OpenDocument->getThumbnail()
#4 /var/www/nextcloud/lib/private/Preview/Generator.php(245): OC\Preview\GeneratorHelper->getThumbnail()
#5 /var/www/nextcloud/lib/private/Preview/Generator.php(140): OC\Preview\Generator->getMaxPreview()
#6 /var/www/nextcloud/lib/private/PreviewManager.php(204): OC\Preview\Generator->generatePreviews()
#7 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(203): OC\PreviewManager->generatePreviews()
#8 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(174): OCA\PreviewGenerator\Command\Generate->parseFile()
#9 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(172): OCA\PreviewGenerator\Command\Generate->parseFolder()
#10 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(155): OCA\PreviewGenerator\Command\Generate->parseFolder()
#11 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(123): OCA\PreviewGenerator\Command\Generate->generateUserPreviews()
#12 /var/www/nextcloud/lib/private/User/Manager.php(646): OCA\PreviewGenerator\Command\Generate->OCA\PreviewGenerator\Command\{closure}()
#13 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(124): OC\User\Manager->callForSeenUsers()
#14 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\PreviewGenerator\Command\Generate->execute()
#15 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#16 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#17 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#18 /var/www/nextcloud/lib/private/Console/Application.php(209): Symfony\Component\Console\Application->run()
#19 /var/www/nextcloud/console.php(99): OC\Console\Application->run()
#20 /var/www/nextcloud/occ(11): require_once('...')
```

**Comment by st3iny** [comment] 2021-11-16 12:49
I can confirm this report. This error appeared in my server logs after the update to Nextcloud v22. However, the error originates in the core/server preview logic and not in the PreviewGenerator app.

**Comment by st3iny** [comment] 2021-11-16 12:49
Closed in favor of https://github.com/nextcloud/server/issues/25340.

**Closed by st3iny** 2021-11-16 12:49 UTC

**Comment by c-schulz-rd13** [comment] 2022-02-13 18:53
Why is this closed and not fixed and way are all related issues building a circle of closed issues?....
I have the same problem with nc 22.2.3.

**Comment by st3iny** [comment] 2022-02-14 09:29
> Why is this closed and not fixed and way are all related issues building a circle of closed issues?.... I have the same problem with nc 22.2.3.

It was closed because it is a duplicate. Please refer to the referenced issue.
