### ISSUE TITLE
previews for majority of images not created

### ISSUE THREAD

**Issue by tincanfury** [nextcloud/previewgenerator#528] opened 2024-12-09 01:46 UTC
[Nextcloud Hub 9](https://nextcloud.com/) (30.0.3)
Nextcloud installed as a docker via 
https://github.com/linuxserver/docker-nextcloud/

I've tried manually running
_occ preview:generate-all -vvv_

and while it says it's generating a preview for the image files less than half my images show previews. running that command multiple times over several days does not appear to help.

**Comment by st3iny** [comment] 2024-12-28 13:19
Previews not being shown in the browser is usually pointing to another problem. Usually, this is caused by Nextcloud not serving the files correctly to your browser.

What exactly do you mean by the previews not showing? Are there grey boxes instead of previews?

Please also check the network log of your browser for failed requests/responses. You can filter by the term `core/preview` to only see the preview requests.

**Comment by tincanfury** [comment] 2024-12-28 19:08
it took a while to find, but there's a setting that limits the size of original image that nextcloud thumbnails  will be created for. The default is 50M, for some reason on my fresh install it was set to 5M. I changed this to 100M and the next morning all my photos had thumbnails.

**Comment by st3iny** [comment] 2024-12-30 08:12
Great news! I'll close the issue then.

**Closed by st3iny** 2024-12-30 08:12 UTC
Labels: bug, 0. to triage, needs info
