### ISSUE TITLE
Problem with preview generation on "ProPhoto RGB" JPEGs

### ISSUE THREAD

**Issue by t3dc** [nextcloud/previewgenerator#201] opened 2020-07-25 12:01 UTC
Hey folks,

This is a cross-post of an issue I opened over on the [nextcloud support channel](https://help.nextcloud.com/t/photo-colors-badly-altered/88115) but I thought this might be a better place to post and get an answer.

I have a series of photos an event photographer is providing me that I would like to share with family using our family nextcloud. Here's the problem, the previews get the colors wrong:
![Screenshot 2020-07-24 at 08 50 04](https://user-images.githubusercontent.com/52919338/88456517-95a45f00-ce7e-11ea-945a-a80bc1027d39.png)

As you can see in the example above, skin tones move from normal and healthy looking to something like the zombie apocalypse.

The source jpegs display beautifully on my computer after syncing from NextCloud, but the previews all look like they do above. I've deleted and recreated all of the previews at command-line (using previewgenerator) and I've followed the guides for changing NextCloud's default previewing behavior. The results remain as above. If I upload a jpeg from my camera, it looks fine. Only jpegs coming from the photographer have an issue. That's what got me looking at color profiles.

The photog is using "ProPhoto RGB" as her colorspace. When I create jpegs, I'm using "sRGB." I can convert her photos from "ProPhoto RGB" to "sRGB" and they preview properly -- but of course there is some generation loss.

Can anyone help me figure out how to generate proper previews from the ProPhoto RGB files? Or even manually replace previews with a batch export from some other program?

Thanks!

**Comment by ShaunCurrier** [comment] 2022-02-01 05:22
Definitely smells like what would happen if the preview generator doesn't respect the color profile when generating the preview.  Instead, it seems like it's reading the image data naively and treating it as though it is sRGB.  In my experience, when non-color-space-aware apps open large color space images the result is colors that look washed-out and lack saturation.  Just like what you show.

Sorry, I can't propose a solution, but thought +1'ing the problem might help eventually.

**Comment by t3dc** [comment] 2022-02-01 08:46
Thanks. In the end, I had the photographer provide two copies, one in sRGB for display and a separate set for print. Would love to see this get fixed, though.

**Comment by t3dc** [comment] 2022-02-01 21:08
Thanks, Richard. I appreciate your following up. Hopefully, we’ll see a fix in gd. :)

**Comment by joshtrichards** [comment] 2024-03-30 16:00
Duplicate of nextcloud/server#22951

**Closed by joshtrichards** 2024-03-30 16:00 UTC
