### ISSUE TITLE
Preview Generator stopped working

### ISSUE THREAD

**Issue by Niemand112233** [nextcloud/previewgenerator#227] opened 2021-03-11 21:30 UTC
Hi,
I tried to run preview:generate-all and after some minutes I get this error:

```
An unhandled exception has been thrown:
ValueError: Invalid or uninitialized Zip object in /var/www/nextcloud/lib/private/Archive/ZIP.php:155
Stack trace:
#0 /var/www/nextcloud/lib/private/Archive/ZIP.php(155): ZipArchive->getStream()
#1 /var/www/nextcloud/lib/private/Preview/Bundled.php(43): OC\Archive\ZIP->extractFile()
#2 /var/www/nextcloud/lib/private/Preview/OpenDocument.php(45): OC\Preview\Bundled->extractThumbnail()
#3 /var/www/nextcloud/lib/private/Preview/GeneratorHelper.php(63): OC\Preview\OpenDocument->getThumbnail()
#4 /var/www/nextcloud/lib/private/Preview/Generator.php(244): OC\Preview\GeneratorHelper->getThumbnail()
#5 /var/www/nextcloud/lib/private/Preview/Generator.php(140): OC\Preview\Generator->getMaxPreview()
#6 /var/www/nextcloud/lib/private/PreviewManager.php(205): OC\Preview\Generator->generatePreviews()
#7 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(203): OC\PreviewManager->generatePreviews()
#8 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(174): OCA\PreviewGenerator\Command\Generate->parseFile()
#9 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(172): OCA\PreviewGenerator\Command\Generate->parseFolder()
#10 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(172): OCA\PreviewGenerator\Command\Generate->parseFolder()
#11 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(172): OCA\PreviewGenerator\Command\Generate->parseFolder()
#12 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(172): OCA\PreviewGenerator\Command\Generate->parseFolder()
#13 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(155): OCA\PreviewGenerator\Command\Generate->parseFolder()
#14 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(123): OCA\PreviewGenerator\Command\Generate->generateUserPreviews()
#15 /var/www/nextcloud/lib/private/User/Manager.php(610): OCA\PreviewGenerator\Command\Generate->OCA\PreviewGenerator\Command\{closure}()
#16 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(124): OC\User\Manager->callForSeenUsers()
#17 /var/www/nextcloud/apps/bookmarks/vendor/symfony/console/Command/Command.php(255): OCA\PreviewGenerator\Command\Generate->execute()
#18 /var/www/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#19 /var/www/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#20 /var/www/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#21 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#22 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#23 /var/www/nextcloud/occ(11): require_once('...')
```

Does anyone have a clue what's the problem?

**Comment by st3iny** [comment] 2021-11-16 12:51
Duplicate of https://github.com/nextcloud/previewgenerator/issues/253.

**Closed by st3iny** 2021-11-16 12:51 UTC
